import 'package:sqflite/sqflite.dart' hide DatabaseException;

import 'package:schedule_plan/core/error/app_exceptions.dart';
import 'package:schedule_plan/core/logging/app_logger.dart';
import 'package:schedule_plan/data/db/app_database.dart';
import 'package:schedule_plan/data/models/todo.dart';

/// 待办数据访问层（readme 3.9 表，模块四 + 模块五 5.4）。
class TodoRepository {
  TodoRepository({Database? database}) : _db = database;

  Database? _db;

  Future<Database> get _database async => _db ??= await AppDatabase.instance();

  /// [autoGenerated] 为 null 表示全部；true 只取智能待办；false 只取通用待办。
  Future<List<Todo>> listTodos({bool? autoGenerated}) async {
    final db = await _database;
    final rows = await db.query(
      'todo',
      where: autoGenerated == null
          ? null
          : 'is_auto_generated = ?',
      whereArgs: autoGenerated == null ? null : <Object?>[autoGenerated ? 1 : 0],
      orderBy: 'is_done ASC, sort_order ASC, id ASC',
    );
    return rows.map(Todo.fromMap).toList();
  }

  Future<int> createTodo(Todo todo) async {
    final db = await _database;
    if (todo.title.trim().isEmpty) {
      throw const ValidationException('待办标题不能为空');
    }
    try {
      final maxOrder = Sqflite.firstIntValue(
            await db.rawQuery('SELECT MAX(sort_order) FROM todo'),
          ) ??
          -1;
      return db.insert('todo', todo.copyWith(sortOrder: maxOrder + 1).toMap());
    } catch (error, stack) {
      AppLogger.e('新建待办失败', error: error, stack: stack);
      throw DatabaseException('新建待办失败：$error', cause: error);
    }
  }

  Future<void> updateTodo(Todo todo) async {
    final db = await _database;
    if (todo.id == null) {
      throw const ValidationException('待办 id 缺失');
    }
    await db.update(
      'todo',
      todo.toMap(),
      where: 'id = ?',
      whereArgs: <Object?>[todo.id],
    );
  }

  Future<void> deleteTodo(int id) async {
    final db = await _database;
    await db.delete('todo', where: 'id = ?', whereArgs: <Object?>[id]);
  }

  /// 拖拽排序结果持久化（模块四 4.4）。
  Future<void> reorder(List<int> orderedIds) async {
    final db = await _database;
    try {
      await db.transaction((txn) async {
        for (var i = 0; i < orderedIds.length; i++) {
          await txn.update(
            'todo',
            <String, Object?>{'sort_order': i},
            where: 'id = ?',
            whereArgs: <Object?>[orderedIds[i]],
          );
        }
      });
    } catch (error, stack) {
      AppLogger.e('保存待办排序失败', error: error, stack: stack);
      throw DatabaseException('保存待办排序失败：$error', cause: error);
    }
  }

  /// 查询某班级是否已有未完成的同类型自动待办，避免重复生成。
  Future<Todo?> findPendingAutoTodo(int classId, String titleKeyword) async {
    final db = await _database;
    final rows = await db.query(
      'todo',
      where: 'related_class_id = ? AND is_auto_generated = 1 AND is_done = 0 '
          "AND title LIKE ?",
      whereArgs: <Object?>[classId, '%$titleKeyword%'],
      limit: 1,
    );
    if (rows.isEmpty) {
      return null;
    }
    return Todo.fromMap(rows.first);
  }

  /// 考勤联动自动完成（模块四 4.5）：
  /// 对应班级本周不再有新增缺勤时，自动标记为已完成。
  Future<int> autoCompleteForClasses(List<int> classIds) async {
    if (classIds.isEmpty) {
      return 0;
    }
    final db = await _database;
    final placeholders = List<String>.filled(classIds.length, '?').join(',');
    try {
      return await db.transaction((txn) async {
        return txn.update(
          'todo',
          <String, Object?>{'is_done': 1},
          where: 'is_auto_generated = 1 AND is_done = 0 '
              'AND related_class_id IN ($placeholders)',
          whereArgs: classIds,
        );
      });
    } catch (error, stack) {
      AppLogger.e('自动完成待办失败', error: error, stack: stack);
      throw DatabaseException('自动完成待办失败：$error', cause: error);
    }
  }
}
