import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'package:schedule_plan/core/constants/app_constants.dart';
import 'package:schedule_plan/core/theme/app_motion.dart';
import 'package:schedule_plan/core/l10n/l10n_extensions.dart';
import 'package:schedule_plan/core/widgets/app_card.dart';
import 'package:schedule_plan/core/widgets/confirm_dialog.dart';
import 'package:schedule_plan/data/models/todo.dart';
import 'package:schedule_plan/data/repositories/todo_repository.dart';

/// 通用待办清单（模块五 5.4）。
///
/// 独立于模块四「智能待办」，不与课表/考勤联动，供教师记录私人事务。
class GeneralTodoPage extends StatefulWidget {
  const GeneralTodoPage({super.key});

  @override
  State<GeneralTodoPage> createState() => _GeneralTodoPageState();
}

class _GeneralTodoPageState extends State<GeneralTodoPage> {
  late Future<List<Todo>> _future;

  @override
  void initState() {
    super.initState();
    _reload();
  }

  void _reload() {
    setState(() {
      _future = context.read<TodoRepository>().listTodos(autoGenerated: false);
    });
  }

  Future<void> _add() async {
    final result = await showAppSheet<String>(
      context: context,
      builder: (_) => const _SimpleTodoForm(),
    );
    if (result == null || result.trim().isEmpty || !mounted) {
      return;
    }
    await context.read<TodoRepository>().createTodo(
          Todo(title: result.trim(), isAutoGenerated: false),
        );
    _reload();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(title: Text(l10n.generalTodoTitle)),
      floatingActionButton: FloatingActionButton(
        onPressed: _add,
        child: const Icon(Icons.add),
      ),
      body: FutureBuilder<List<Todo>>(
        future: _future,
        builder: (context, snapshot) {
          final todos = snapshot.data ?? const <Todo>[];
          if (todos.isEmpty) {
            return Center(child: Text(l10n.emptyTodo));
          }
          return ListView.builder(
            padding: const EdgeInsets.all(AppConstants.spaceL),
            itemCount: todos.length,
            itemBuilder: (context, index) {
              final todo = todos[index];
              return Padding(
                padding: const EdgeInsets.only(bottom: AppConstants.spaceS),
                child: AppCard(
                  child: Row(
                    children: <Widget>[
                      Checkbox(
                        value: todo.isDone,
                        onChanged: (_) async {
                          await context.read<TodoRepository>().updateTodo(
                                todo.copyWith(isDone: !todo.isDone),
                              );
                          _reload();
                        },
                      ),
                      Expanded(
                        child: AnimatedDefaultTextStyle(
                          duration: AppMotion.instant,
                          style: (theme.textTheme.titleSmall ?? const TextStyle())
                              .copyWith(
                            decoration: todo.isDone
                                ? TextDecoration.lineThrough
                                : TextDecoration.none,
                          ),
                          child: Text(todo.title),
                        ),
                      ),
                      IconButton(
                        icon: const Icon(Icons.delete_outline),
                        onPressed: () async {
                          final confirmed = await showAppConfirm(
                            context: context,
                            title: l10n.delete,
                            body: l10n.todoDeleteConfirmBody,
                            danger: true,
                          );
                          if (!confirmed || !context.mounted) {
                            return;
                          }
                          await context
                              .read<TodoRepository>()
                              .deleteTodo(todo.id!);
                          _reload();
                        },
                      ),
                    ],
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}

class _SimpleTodoForm extends StatefulWidget {
  const _SimpleTodoForm();

  @override
  State<_SimpleTodoForm> createState() => _SimpleTodoFormState();
}

class _SimpleTodoFormState extends State<_SimpleTodoForm> {
  final TextEditingController _controller = TextEditingController();
  String? _error;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    return AppCard(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Text(l10n.todoAdd, style: Theme.of(context).textTheme.titleMedium),
          const SizedBox(height: AppConstants.spaceM),
          TextField(
            controller: _controller,
            decoration: InputDecoration(
              labelText: l10n.todoAdd,
              errorText: _error,
            ),
          ),
          const SizedBox(height: AppConstants.spaceL),
          FilledButton(
            onPressed: () {
              if (_controller.text.trim().isEmpty) {
                setState(() => _error = l10n.todoTitleRequired);
                return;
              }
              Navigator.of(context).pop(_controller.text);
            },
            child: Text(l10n.save),
          ),
        ],
      ),
    );
  }
}
