import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'package:schedule_plan/core/constants/app_constants.dart';
import 'package:schedule_plan/core/theme/app_motion.dart';
import 'package:schedule_plan/core/l10n/l10n_extensions.dart';
import 'package:schedule_plan/core/logging/app_logger.dart';
import 'package:schedule_plan/core/utils/date_utils.dart' as app_dates;
import 'package:schedule_plan/core/widgets/app_card.dart';
import 'package:schedule_plan/core/widgets/confirm_dialog.dart';
import 'package:schedule_plan/data/models/todo.dart';
import 'package:schedule_plan/data/repositories/attendance_repository.dart';
import 'package:schedule_plan/data/repositories/class_repository.dart';
import 'package:schedule_plan/data/repositories/todo_repository.dart';

/// 待办页（模块四：智能待办 + 模块五 5.4：通用清单）。
class TodoPage extends StatefulWidget {
  const TodoPage({super.key});

  @override
  State<TodoPage> createState() => _TodoPageState();
}

class _TodoPageState extends State<TodoPage> with SingleTickerProviderStateMixin {
  late TabController _tabController;
  late Future<List<Todo>> _smartFuture;
  late Future<List<Todo>> _generalFuture;
  bool _showCompleted = false;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
    _reload();
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  void _reload() {
    final repository = context.read<TodoRepository>();
    _smartFuture = repository.listTodos(autoGenerated: true).then((value) async {
      await _syncAutoGenerated();
      return repository.listTodos(autoGenerated: true);
    });
    _generalFuture = repository.listTodos(autoGenerated: false);
    setState(() {});
  }

  /// 考勤联动：自动生成待办与自动完成（模块四 4.1 / 4.5）。
  Future<void> _syncAutoGenerated() async {
    final l10n = context.l10n;
    final repository = context.read<TodoRepository>();
    final classRepo = context.read<ClassRepository>();
    final attendanceRepo = context.read<AttendanceRepository>();
    final classes = await classRepo.listClasses();
    final now = DateTime.now();
    final weekStart =
        app_dates.DateUtils.formatDate(app_dates.DateUtils.startOfWeek(now));
    final weekEnd = app_dates.DateUtils.formatDate(
      app_dates.DateUtils.startOfWeek(now).add(const Duration(days: 6)),
    );
    final counts = await attendanceRepo.weeklyAbsenceCountByClass(
          fromDate: weekStart,
          toDate: weekEnd,
        );
    final classesWithAbsence = <int>[];
    try {
      for (final item in classes) {
        final count = counts[item.id] ?? 0;
        if (count < AppConstants.autoTodoAbsenceThreshold) {
          continue;
        }
        classesWithAbsence.add(item.id!);
        final title = l10n.autoTodoTitle(item.name);
        final existing =
            await repository.findPendingAutoTodo(item.id!, item.name);
        if (existing == null) {
          await repository.createTodo(
            Todo(
              title: title,
              priority: TodoPriority.high,
              isAutoGenerated: true,
              relatedClassId: item.id,
            ),
          );
        }
      }
      // 对应班级本周不再有新增缺勤时，自动标记为已完成
      final resolved = classes
          .where((item) => !classesWithAbsence.contains(item.id))
          .map((item) => item.id!)
          .toList();
      await repository.autoCompleteForClasses(resolved);
    } catch (error, stack) {
      AppLogger.e('同步自动生成待办失败', error: error, stack: stack);
    }
  }

  Future<void> _toggle(Todo todo) async {
    await context.read<TodoRepository>().updateTodo(todo.copyWith(isDone: !todo.isDone));
    _reload();
  }

  Future<void> _delete(Todo todo) async {
    final l10n = context.l10n;
    final repository = context.read<TodoRepository>();
    final confirmed = await showAppConfirm(
      context: context,
      title: l10n.delete,
      body: l10n.todoDeleteConfirmBody,
      danger: true,
    );
    if (!confirmed) {
      return;
    }
    await repository.deleteTodo(todo.id!);
    _reload();
  }

  Future<void> _add({required bool autoGenerated}) async {
    final result = await showAppSheet<Todo>(
      context: context,
      builder: (_) => _TodoForm(isAutoGenerated: autoGenerated),
    );
    if (result == null || !mounted) {
      return;
    }
    await context.read<TodoRepository>().createTodo(result);
    _reload();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.todoTitle),
        bottom: TabBar(
          controller: _tabController,
          tabs: <Tab>[Tab(text: l10n.todoSmart), Tab(text: l10n.todoGeneral)],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _add(autoGenerated: _tabController.index == 0),
        child: const Icon(Icons.add),
      ),
      body: TabBarView(
        controller: _tabController,
        children: <Widget>[
          _buildList(_smartFuture),
          _buildList(_generalFuture),
        ],
      ),
    );
  }

  Widget _buildList(Future<List<Todo>> future) {
    final l10n = context.l10n;
    return FutureBuilder<List<Todo>>(
      future: future,
      builder: (context, snapshot) {
        final todos = snapshot.data ?? const <Todo>[];
        if (todos.isEmpty) {
          return Center(child: Text(l10n.emptyTodo));
        }
        final pending = todos.where((item) => !item.isDone).toList();
        final done = todos.where((item) => item.isDone).toList();
        return ListView(
          padding: const EdgeInsets.only(bottom: 80),
          children: <Widget>[
            // 拖拽排序：长按触发，结果本地持久化（模块四 4.4）
            ReorderableListView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              padding: const EdgeInsets.all(AppConstants.spaceL),
              itemCount: pending.length,
              onReorder: (oldIndex, newIndex) async {
                if (newIndex > oldIndex) {
                  newIndex -= 1;
                }
                final item = pending.removeAt(oldIndex);
                pending.insert(newIndex, item);
                await context
                    .read<TodoRepository>()
                    .reorder(pending.map((e) => e.id!).toList());
                _reload();
              },
              itemBuilder: (context, index) =>
                  _buildTile(pending[index], key: ValueKey<int>(pending[index].id!)),
            ),
            if (done.isNotEmpty)
              TextButton(
                onPressed: () => setState(() => _showCompleted = !_showCompleted),
                child: Text(l10n.todoCompletedSection(done.length)),
              ),
            if (done.isNotEmpty && _showCompleted)
              for (final todo in done)
                _buildTile(todo, key: ValueKey<int>(todo.id!)),
          ],
        );
      },
    );
  }

  Widget _buildTile(Todo todo, {required Key key}) {
    final l10n = context.l10n;
    final theme = Theme.of(context);
    return Padding(
      key: key,
      padding: const EdgeInsets.only(bottom: AppConstants.spaceS),
      child: AppCard(
        child: Row(
          children: <Widget>[
            Checkbox(
              value: todo.isDone,
              onChanged: (_) => _toggle(todo),
            ),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  // 勾选完成后有删除线动效（模块四 4.3）
                  AnimatedDefaultTextStyle(
                    duration: AppMotion.instant,
                    style: (theme.textTheme.titleSmall ?? const TextStyle()).copyWith(
                      decoration:
                          todo.isDone ? TextDecoration.lineThrough : TextDecoration.none,
                      color: todo.isDone
                          ? theme.colorScheme.onSurfaceVariant
                          : theme.colorScheme.onSurface,
                    ),
                    child: Text(todo.title),
                  ),
                  if (todo.isAutoGenerated && todo.isDone)
                    Text(
                      l10n.todoAutoCompleted,
                      style: theme.textTheme.labelSmall,
                    ),
                ],
              ),
            ),
            IconButton(
              icon: const Icon(Icons.delete_outline),
              onPressed: () => _delete(todo),
            ),
          ],
        ),
      ),
    );
  }
}

class _TodoForm extends StatefulWidget {
  const _TodoForm({required this.isAutoGenerated});

  final bool isAutoGenerated;

  @override
  State<_TodoForm> createState() => _TodoFormState();
}

class _TodoFormState extends State<_TodoForm> {
  final TextEditingController _title = TextEditingController();
  final TextEditingController _description = TextEditingController();
  TodoPriority _priority = TodoPriority.medium;
  DateTime? _dueDate;
  String? _titleError;

  @override
  void dispose() {
    _title.dispose();
    _description.dispose();
    super.dispose();
  }

  void _submit() {
    final l10n = context.l10n;
    if (_title.text.trim().isEmpty) {
      setState(() => _titleError = l10n.todoTitleRequired);
      return;
    }
    Navigator.of(context).pop(
      Todo(
        title: _title.text.trim(),
        description:
            _description.text.trim().isEmpty ? null : _description.text.trim(),
        priority: _priority,
        dueDate: _dueDate?.millisecondsSinceEpoch,
        isAutoGenerated: widget.isAutoGenerated,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    return AppCard(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Text(l10n.todoAdd, style: Theme.of(context).textTheme.titleMedium),
          const SizedBox(height: AppConstants.spaceM),
          TextField(
            controller: _title,
            decoration: InputDecoration(
              labelText: l10n.todoAdd,
              errorText: _titleError,
            ),
          ),
          const SizedBox(height: AppConstants.spaceM),
          TextField(
            controller: _description,
            decoration: InputDecoration(labelText: l10n.todoDescription),
          ),
          const SizedBox(height: AppConstants.spaceM),
          DropdownButtonFormField<TodoPriority>(
            initialValue: _priority,
            decoration: InputDecoration(labelText: l10n.todoPriority),
            items: <DropdownMenuItem<TodoPriority>>[
              DropdownMenuItem<TodoPriority>(
                value: TodoPriority.high,
                child: Text(l10n.priorityHigh),
              ),
              DropdownMenuItem<TodoPriority>(
                value: TodoPriority.medium,
                child: Text(l10n.priorityMedium),
              ),
              DropdownMenuItem<TodoPriority>(
                value: TodoPriority.low,
                child: Text(l10n.priorityLow),
              ),
            ],
            onChanged: (value) => setState(() => _priority = value ?? _priority),
          ),
          const SizedBox(height: AppConstants.spaceM),
          OutlinedButton.icon(
            icon: const Icon(Icons.event_outlined),
            label: Text(_dueDate == null
                ? l10n.todoDueDate
                : app_dates.DateUtils.formatDate(_dueDate!)),
            onPressed: () async {
              final picked = await showDatePicker(
                context: context,
                firstDate: DateTime(2000),
                lastDate: DateTime(2100),
              );
              if (picked != null) {
                setState(() => _dueDate = picked);
              }
            },
          ),
          const SizedBox(height: AppConstants.spaceL),
          FilledButton(onPressed: _submit, child: Text(l10n.save)),
        ],
      ),
    );
  }
}
