/// 待办优先级（readme 3.9 表）。
enum TodoPriority {
  high,
  medium,
  low;

  String get storageKey => name;

  static TodoPriority fromStorage(String? value) => TodoPriority.values.firstWhere(
        (item) => item.name == value,
        orElse: () => TodoPriority.medium,
      );

  /// 排序权重：高优先级排在前面。
  int get weight => switch (this) {
        TodoPriority.high => 0,
        TodoPriority.medium => 1,
        TodoPriority.low => 2,
      };
}

/// 待办（readme 3.9 表 todo）。
///
/// 同时承载：
/// - 模块四「智能待办」（is_auto_generated = 1，与课表/考勤联动）
/// - 模块五 5.4「通用待办」（is_auto_generated = 0，不与课表/考勤联动）
class Todo {
  const Todo({
    this.id,
    required this.title,
    this.description,
    this.priority = TodoPriority.medium,
    this.dueDate,
    this.isDone = false,
    this.isAutoGenerated = false,
    this.relatedClassId,
    this.sortOrder = 0,
  });

  final int? id;
  final String title;
  final String? description;
  final TodoPriority priority;

  /// 毫秒时间戳
  final int? dueDate;
  final bool isDone;
  final bool isAutoGenerated;

  /// 自动生成待办关联的班级
  final int? relatedClassId;
  final int sortOrder;

  Todo copyWith({
    int? id,
    String? title,
    String? description,
    TodoPriority? priority,
    int? dueDate,
    bool? isDone,
    bool? isAutoGenerated,
    int? relatedClassId,
    int? sortOrder,
  }) {
    return Todo(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      priority: priority ?? this.priority,
      dueDate: dueDate ?? this.dueDate,
      isDone: isDone ?? this.isDone,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      relatedClassId: relatedClassId ?? this.relatedClassId,
      sortOrder: sortOrder ?? this.sortOrder,
    );
  }

  Map<String, Object?> toMap() => <String, Object?>{
        if (id != null) 'id': id,
        'title': title,
        'description': description,
        'priority': priority.storageKey,
        'due_date': dueDate,
        'is_done': isDone ? 1 : 0,
        'is_auto_generated': isAutoGenerated ? 1 : 0,
        'related_class_id': relatedClassId,
        'sort_order': sortOrder,
      };

  static Todo fromMap(Map<String, Object?> map) => Todo(
        id: map['id'] as int?,
        title: map['title'] as String,
        description: map['description'] as String?,
        priority: TodoPriority.fromStorage(map['priority'] as String?),
        dueDate: map['due_date'] as int?,
        isDone: (map['is_done'] as int? ?? 0) == 1,
        isAutoGenerated: (map['is_auto_generated'] as int? ?? 0) == 1,
        relatedClassId: map['related_class_id'] as int?,
        sortOrder: map['sort_order'] as int? ?? 0,
      );
}
